import { Router } from "express";
import * as gymController from "../controllers/gym.controller.js";
import { ROLES } from "../constants/roles.js";
import { authenticate, authorize } from "../middlewares/auth.middleware.js";
import { requireActiveOwnerSubscription } from "../middlewares/subscription.middleware.js";
import { validate } from "../middlewares/validate.middleware.js";
import { asyncHandler } from "../utils/asyncHandler.js";
import { addTrainerSchema, assetAddTrainerSchema, assetCouponDeleteSchema, assetCouponValidateSchema, assetCouponsListSchema, assetEnrollMemberSchema, assetMemberEmailOtpSendSchema, assetMemberEmailOtpVerifySchema, assetMemberLookupSchema, assetPlanCreateSchema, assetPlanDeleteSchema, assetPlanUpdateSchema, assetRemoveTrainerSchema, assetTrainerEmailOtpSendSchema, assetTrainerEmailOtpVerifySchema, assetTrainerLookupSchema, assetTransactionsCreateSchema, assetTransactionsDeleteSchema, assetTransactionsListSchema, assetTransactionsUpdateSchema, createGymSchema, enrollMemberSchema, gymAdminStatusSchema, gymIdSchema, memberEmailOtpSendSchema, memberEmailOtpVerifySchema, memberLookupSchema, ownerAnalyticsSchema, removeTrainerSchema, setGymAssetPermissionsSchema, setGymAssetSchema, setGymEquipmentSchema, trainerEmailOtpSendSchema, trainerEmailOtpVerifySchema, trainerLookupSchema } from "../validators/gym.validator.js";

const router = Router();

router.get("/public", asyncHandler(gymController.getPublicGyms));
router.post("/create", authenticate, authorize(ROLES.OWNER, ROLES.ADMIN), requireActiveOwnerSubscription, validate(createGymSchema), asyncHandler(gymController.createGym));
router.get("/my", authenticate, authorize(ROLES.OWNER, ROLES.ADMIN), requireActiveOwnerSubscription, asyncHandler(gymController.getMyGyms));
router.get("/my/analytics", authenticate, authorize(ROLES.OWNER), requireActiveOwnerSubscription, validate(ownerAnalyticsSchema), asyncHandler(gymController.getOwnerAnalytics));
router.get("/all", authenticate, authorize(ROLES.ADMIN), asyncHandler(gymController.getAllGyms));
router.patch("/admin/:gymId/status", authenticate, authorize(ROLES.ADMIN), validate(gymAdminStatusSchema), asyncHandler(gymController.setGymActiveStatus));
router.delete("/admin/:gymId", authenticate, authorize(ROLES.ADMIN), validate(gymIdSchema), asyncHandler(gymController.deleteGym));
router.get("/my/:gymId", authenticate, authorize(ROLES.OWNER, ROLES.ADMIN), requireActiveOwnerSubscription, validate(gymIdSchema), asyncHandler(gymController.getGymManagement));
router.get("/asset/:gymId", validate(gymIdSchema), asyncHandler(gymController.getGymManagementByAsset));
router.post("/asset/:gymId/plans", validate(assetPlanCreateSchema), asyncHandler(gymController.createPlanByAsset));
router.put("/asset/:gymId/plans/:planId", validate(assetPlanUpdateSchema), asyncHandler(gymController.updatePlanByAsset));
router.delete("/asset/:gymId/plans/:planId", validate(assetPlanDeleteSchema), asyncHandler(gymController.removePlanByAsset));
router.put("/asset/:gymId/equipment", validate(setGymEquipmentSchema), asyncHandler(gymController.setGymEquipmentByAsset));
router.post("/asset/:gymId/trainer-lookup", validate(assetTrainerLookupSchema), asyncHandler(gymController.lookupTrainerByAsset));
router.post("/asset/:gymId/trainer-email-otp/send", validate(assetTrainerEmailOtpSendSchema), asyncHandler(gymController.sendTrainerEmailOtpByAsset));
router.post("/asset/:gymId/trainer-email-otp/verify", validate(assetTrainerEmailOtpVerifySchema), asyncHandler(gymController.verifyTrainerEmailOtpByAsset));
router.post("/asset/:gymId/add-trainer", validate(assetAddTrainerSchema), asyncHandler(gymController.addTrainerToGymByAsset));
router.delete("/asset/:gymId/remove-trainer", validate(assetRemoveTrainerSchema), asyncHandler(gymController.removeTrainerFromGymByAsset));
router.post("/asset/:gymId/member-lookup", validate(assetMemberLookupSchema), asyncHandler(gymController.lookupMemberByAsset));
router.post("/asset/:gymId/member-email-otp/send", validate(assetMemberEmailOtpSendSchema), asyncHandler(gymController.sendMemberEmailOtpByAsset));
router.post("/asset/:gymId/member-email-otp/verify", validate(assetMemberEmailOtpVerifySchema), asyncHandler(gymController.verifyMemberEmailOtpByAsset));
router.post("/asset/:gymId/member-enroll", validate(assetEnrollMemberSchema), asyncHandler(gymController.enrollMemberByAsset));
router.post("/asset/:gymId/coupon/validate", validate(assetCouponValidateSchema), asyncHandler(gymController.validateCouponByAsset));
router.get("/asset/:gymId/coupons", validate(assetCouponsListSchema), asyncHandler(gymController.listCouponsByAsset));
router.delete("/asset/:gymId/coupons/:couponId", validate(assetCouponDeleteSchema), asyncHandler(gymController.disableCouponByAsset));
router.get("/asset/:gymId/transactions", validate(assetTransactionsListSchema), asyncHandler(gymController.listTransactionsByAsset));
router.post("/asset/:gymId/transactions", validate(assetTransactionsCreateSchema), asyncHandler(gymController.createTransactionByAsset));
router.put("/asset/:gymId/transactions/:transactionId", validate(assetTransactionsUpdateSchema), asyncHandler(gymController.updateTransactionByAsset));
router.delete("/asset/:gymId/transactions/:transactionId", validate(assetTransactionsDeleteSchema), asyncHandler(gymController.deleteTransactionByAsset));
router.put("/my/:gymId/equipment", authenticate, authorize(ROLES.OWNER, ROLES.ADMIN), requireActiveOwnerSubscription, validate(setGymEquipmentSchema), asyncHandler(gymController.setGymEquipment));
router.put("/my/:gymId/asset", authenticate, authorize(ROLES.OWNER, ROLES.ADMIN), requireActiveOwnerSubscription, validate(setGymAssetSchema), asyncHandler(gymController.setGymAssetCredentials));
router.get("/my/:gymId/asset-permissions", authenticate, authorize(ROLES.OWNER, ROLES.ADMIN), requireActiveOwnerSubscription, validate(gymIdSchema), asyncHandler(gymController.getGymAssetPermissions));
router.put("/my/:gymId/asset-permissions", authenticate, authorize(ROLES.OWNER, ROLES.ADMIN), requireActiveOwnerSubscription, validate(setGymAssetPermissionsSchema), asyncHandler(gymController.setGymAssetPermissions));
router.post("/trainer-lookup", authenticate, authorize(ROLES.OWNER, ROLES.ADMIN), requireActiveOwnerSubscription, validate(trainerLookupSchema), asyncHandler(gymController.lookupTrainer));
router.post("/trainer-email-otp/send", authenticate, authorize(ROLES.OWNER, ROLES.ADMIN), requireActiveOwnerSubscription, validate(trainerEmailOtpSendSchema), asyncHandler(gymController.sendTrainerEmailOtp));
router.post("/trainer-email-otp/verify", authenticate, authorize(ROLES.OWNER, ROLES.ADMIN), requireActiveOwnerSubscription, validate(trainerEmailOtpVerifySchema), asyncHandler(gymController.verifyTrainerEmailOtp));
router.post("/add-trainer", authenticate, authorize(ROLES.OWNER, ROLES.ADMIN), requireActiveOwnerSubscription, validate(addTrainerSchema), asyncHandler(gymController.addTrainer));
router.delete("/remove-trainer", authenticate, authorize(ROLES.OWNER, ROLES.ADMIN), requireActiveOwnerSubscription, validate(removeTrainerSchema), asyncHandler(gymController.removeTrainer));
router.post("/member-lookup", authenticate, authorize(ROLES.OWNER, ROLES.ADMIN), requireActiveOwnerSubscription, validate(memberLookupSchema), asyncHandler(gymController.lookupMember));
router.post("/member-email-otp/send", authenticate, authorize(ROLES.OWNER, ROLES.ADMIN), requireActiveOwnerSubscription, validate(memberEmailOtpSendSchema), asyncHandler(gymController.sendMemberEmailOtp));
router.post("/member-email-otp/verify", authenticate, authorize(ROLES.OWNER, ROLES.ADMIN), requireActiveOwnerSubscription, validate(memberEmailOtpVerifySchema), asyncHandler(gymController.verifyMemberEmailOtp));
router.post("/member-enroll", authenticate, authorize(ROLES.OWNER, ROLES.ADMIN), requireActiveOwnerSubscription, validate(enrollMemberSchema), asyncHandler(gymController.enrollMember));
router.get("/qr/:gymId", authenticate, validate(gymIdSchema), asyncHandler(gymController.getGymQr));

export default router;
