import mongoose from "mongoose";

const booleanDefault = { type: Boolean, default: false };

const userProfileSchema = new mongoose.Schema(
  {
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      unique: true,
      index: true,
    },
    age: Number,
    gender: String,
    fitnessGoal: String,
    occupationType: String,
    location: String,
    locationArea: String,
    locationCity: String,
    locationState: String,
    locationCountry: String,
    locationCoordinates: {
      latitude: Number,
      longitude: Number,
    },
    speakingLanguages: [String],
    speakingLanguageOther: String,
    heightCm: Number,
    weightKg: Number,
    bodyFatPercentage: Number,
    neckCm: Number,
    waistCm: Number,
    hipCm: Number,
    chestCm: Number,
    bodyType: String,
    fatDistributionType: String,
    sleepDurationHours: Number,
    sleepTiming: String,
    sleepQuality: Number,
    screenTimeBeforeBedMinutes: Number,
    dietType: String,
    mealPattern: String,
    eatingBehavior: String,
    emotionalEating: booleanDefault,
    lateNightEating: booleanDefault,
    bingeEating: booleanDefault,
    waterIntakeLiters: Number,
    sugarIntakeLevel: String,
    caffeineIntake: String,
    medications: String,
    allergies: String,
    medicalNotes: String,
    otherConditions: String,
    otherInjuries: String,
    conditions: {
      diabetes: booleanDefault,
      thyroid: booleanDefault,
      pcos: booleanDefault,
      bp: booleanDefault,
    },
    injuries: {
      knee: booleanDefault,
      back: booleanDefault,
      shoulder: booleanDefault,
    },
    trainerExperience: [
      {
        gymName: String,
        location: String,
        years: Number,
      },
    ],
    trainerSpecializations: [String],
    trainerSpecializationOther: String,
    trainerCertifications: [String],
    trainerCertificationOther: String,
    trainerEducation: String,
    trainerBodyTypeExpertise: [String],
    trainerTargetAudience: [String],
    trainerTargetAudienceOther: String,
    trainerProgramTypes: [String],
    trainerProgramTypeOther: String,
    trainerLocationMode: String,
    trainerLanguages: [String],
    trainerLanguageOther: String,
  },
  { timestamps: true, versionKey: false },
);

export const UserProfile = mongoose.model("UserProfile", userProfileSchema);
